default-lease-time 300;
max-lease-time 7200;
lease-file-name "/var/dhcptest.leases";
ddns-update-style interim;
authoritative;
log-facility local7;

subnet 10.0.10.0 netmask 255.255.255.0 {
	range 10.0.10.11 10.0.10.20;
	option routers 10.0.10.1;
}

host fixed {
	hardware ethernet 42:00:aa:00:00:01;
	fixed-address 10.0.10.30;
}

