# Enable UDP
module(load="imudp")
input(type="imudp" port="514")

# Enable TCP
module(load="imtcp")
input(type="imtcp" port="514")

# Remote logs per host
$template RemoteLogs,"/var/log/remote/%HOSTNAME%.log"
*.* ?RemoteLogs
