
# ─ Global options ──────────────
default-lease-time 600;
max-lease-time 7200;
authoritative;

# DNS server
option domain-name-servers 10.0.10.11;
option domain-name "office.local";

# Logging of lease information
log-facility local7;


# ── SUBNET: Servers (10.0.10.0/24) ─────────────────────────
subnet 10.0.10.0 netmask 255.255.255.0 {
    option routers 10.0.10.1;
}

host DNS-Server {
    hardware ethernet 42:00:aa:00:00:11;
    fixed-address 10.0.10.11;
    option host-name "dns-server";
}
host File-Server {
    hardware ethernet 42:00:aa:00:00:12;
    fixed-address 10.0.10.12;
    option host-name "file-server";
}
host Web-Server {
    hardware ethernet 42:00:aa:00:00:13;
    fixed-address 10.0.10.13;
    option host-name "web-server";
}


# ── SUBNET: Finance (10.0.20.0/24) ──────────────────────────
subnet 10.0.20.0 netmask 255.255.255.0 {
    range 10.0.20.20 10.0.20.50;
    option routers 10.0.20.1;           # FIN-router eth0
    option subnet-mask 255.255.255.0;
    option broadcast-address 10.0.20.255;
    default-lease-time 600;
    max-lease-time 3600;
}


# ── SUBNET: HR (10.0.30.0/24) ───────────────────────────────
subnet 10.0.30.0 netmask 255.255.255.0 {
    range 10.0.30.20 10.0.30.50;
    option routers 10.0.30.1;           # HR-router eth0
    option subnet-mask 255.255.255.0;
    option broadcast-address 10.0.30.255;
    default-lease-time 600;
    max-lease-time 3600;
}


# ── SUBNET: IT (10.0.40.0/24) ───────────────────────────────
subnet 10.0.40.0 netmask 255.255.255.0 {
    range 10.0.40.20 10.0.40.50;
    option routers 10.0.40.1;           # IT-router eth0
    option subnet-mask 255.255.255.0;
    option broadcast-address 10.0.40.255;
    default-lease-time 600;
    max-lease-time 3600;
}


# ── SUBNET: Mgmt (10.0.50.0/24) ─────────────────────────────
subnet 10.0.50.0 netmask 255.255.255.0 {
    range 10.0.50.20 10.0.50.50;
    option routers 10.0.50.1;           # Mgmt-router eth0
    option subnet-mask 255.255.255.0;
    option broadcast-address 10.0.50.255;
    default-lease-time 600;
    max-lease-time 3600;
}

# Static reservations – Attacker (MGMT-pc1) i Syslog
host MGMT-pc1 {
    hardware ethernet 42:00:aa:00:00:1f;
    fixed-address 10.0.50.100;
    option host-name "mgmt-pc1";
}
host Syslog {
    hardware ethernet 42:00:aa:00:00:20;
    fixed-address 10.0.50.50;
    option host-name "syslog";
}

